name: 'install-dependencies'
description: 'Install dependencies required for building Teide'

inputs:
  preset:
    description: 'CMake preset used to build vcpkg packages'
    required: true
  apt-packages:
    description: 'Additional packages to install with apt (Linux only)'
    required: false

runs:
  using: composite
  steps:
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: '716c3524a54f1f50a25d16a4cdd360f5a7fcc150'
        appendedCacheKey: ${{inputs.preset}}

    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: latest
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - if: ${{runner.os == 'Linux' && inputs.apt-packages != ''}}
      name: Install apt packages
      shell: bash
      run: |
        # If clang packages requested, add the appropriate llvm repository
        LLVM_VERSIONS=$(echo ${{inputs.apt-packages}} | tr ' ' '\n' | sed -n 's/^clang.*-\([1-9][0-9]*\)$/\1/p' | sort | uniq)
        for VERSION in $LLVM_VERSIONS; do
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          UBUNTU_CODENAME=`sudo cat /etc/os-release | sed -n s/UBUNTU_CODENAME=//p`
          REPO="deb http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-${VERSION} main"
          echo Adding repository "${REPO}"
          sudo add-apt-repository "${REPO}"
        done
        sudo apt-get update
        sudo apt-get install -y ${{inputs.apt-packages}}
