name: 'install-dependencies'
description: 'Install dependencies required for building Teide'

inputs:
  extra-packages:
    description: 'Additional packages to install with apt-get (Linux) or chocolatey (Windows)'
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "::group::Install problem matchers"
        echo "::add-matcher::.github/msvc-problem-matcher.json"
        echo "-- .github/msvc-problem-matcher.json --"
        cat ".github/msvc-problem-matcher.json"
        curl https://raw.githubusercontent.com/microsoft/vscode-cpptools/refs/heads/main/Extension/package.json 2>/dev/null \
        | jq '{ problemMatcher: .contributes.problemMatchers[0] | [{owner,pattern:[.pattern]}] }' \
          > gcc-problem-matcher.json
        echo "-- gcc-problem-matcher.json --"
        cat gcc-problem-matcher.json
        echo "::add-matcher::gcc-problem-matcher.json"
        echo "::endgroup::"

    # - uses: ammaraskar/gcc-problem-matcher@master

    - if: ${{inputs.extra-packages != ''}}
      shell: bash
      run: |
        bash .github/scripts/install-apt.sh ${{ inputs.extra-packages }}
