name: 'install-dependencies'
description: 'Install dependencies required for building Teide'

inputs:
  preset:
    description: 'CMake preset used to build vcpkg packages'
    required: true

runs:
  using: composite
  steps:
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: '716c3524a54f1f50a25d16a4cdd360f5a7fcc150'
        appendedCacheKey: ${{inputs.preset}}

    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.2.198.1
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true
