name: 'install-dependencies'
description: 'Install dependencies required for building Teide'

inputs:
  extra-packages:
    description: 'Additional packages to install with apt-get (Linux) or chocolatey (Windows)'
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "::group::Install problem matchers"
        echo "::add-matcher::.github/msvc-problem-matcher.json"

    - uses: ammaraskar/gcc-problem-matcher@master

    - shell: bash
      run: |
        echo "::endgroup::"
        echo "::group::Setup Vulkan SDK"

    - uses: edvn0/setup-vulkan-sdk@v1.3.0
      with:
        vulkan-query-version: 1.3.243.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - shell: bash
      run: echo "::endgroup::"

    - if: ${{runner.os == 'Windows' && inputs.extra-packages != ''}}
      shell: pwsh
      run: |
        echo "::group::Install chocolatey packages"
        choco install --ignorepackageexitcodes ${{inputs.extra-packages}}
        $env:ChocolateyInstall = Convert-Path "$((Get-Command choco).Path)\..\.."
        Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        refreshenv
        echo PATH:
        echo $env:path -split ";"
        echo "::endgroup::"

    - if: ${{runner.os == 'Linux' && inputs.extra-packages != ''}}
      shell: bash
      run: |
        echo "::group::Install apt packages"
        # If clang packages requested, add the appropriate llvm repository
        LLVM_VERSIONS=$(echo ${{inputs.extra-packages}} | tr ' ' '\n' | sed -n 's/^clang.*-\([1-9][0-9]*\)$/\1/p' | sort | uniq)
        if [ -n "${LLVM_VERSIONS}" ]; then
          echo "Clang requested, adding LLVM repositories..."
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          UBUNTU_CODENAME=`sudo cat /etc/os-release | sed -n s/UBUNTU_CODENAME=//p`
          for VERSION in ${LLVM_VERSIONS}; do
            REPO="deb http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-${VERSION} main"
            echo Adding repository "${REPO}"
            sudo add-apt-repository "${REPO}"
          done
          sudo apt-get update
          sudo apt-get install -y llvm
        fi
        echo "Installing apt packages: ${{inputs.extra-packages}}"
        sudo apt-get install -y ${{inputs.extra-packages}}
        echo "::endgroup::"
