name: 'install-tools'
description: 'Install tools required for building on CI'

inputs:
  extra-packages:
    description: 'Additional packages to install'
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        # Install tools
        echo "::group::Install problem matchers"
        echo "::add-matcher::.github/msvc-problem-matcher.json"
        echo "-- .github/msvc-problem-matcher.json --"
        cat ".github/msvc-problem-matcher.json"
        curl https://raw.githubusercontent.com/microsoft/vscode-cpptools/refs/heads/main/Extension/package.json 2>/dev/null \
        | jq '{ problemMatcher: .contributes.problemMatchers[0] | [{owner,pattern:[.pattern]}] }' \
          > gcc-problem-matcher.json
        echo "-- gcc-problem-matcher.json --"
        cat gcc-problem-matcher.json
        echo "::add-matcher::gcc-problem-matcher.json"
        echo "::endgroup::"
        echo

        if ${{inputs.extra-packages != ''}}; then
          bash .github/scripts/install-tools.sh ${{ inputs.extra-packages }}
        fi
