if(DEFINED ENV{TEIDE_PREBUILT_PACKAGES_DIR})
    include($ENV{TEIDE_PREBUILT_PACKAGES_DIR}/scripts/buildsystems/vcpkg.cmake)
else()
    include(${CMAKE_CURRENT_LIST_DIR}/../../../external/vcpkg/scripts/buildsystems/vcpkg.cmake)
endif()
