function(target_enable_sanitizer target sanitizer)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        if(sanitizer STREQUAL "ASAN")
            target_compile_options(${target} PRIVATE -ggdb -fsanitize=address -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
        elseif(sanitizer STREQUAL "UBSAN")
            set(checks undefined,float-divide-by-zero,implicit-conversion,nullability)
            target_compile_options(${target} PRIVATE -g -fsanitize=${checks} -fno-sanitize-recover=${checks})
            target_link_options(${target} PRIVATE -fsanitize=${checks} -fno-sanitize-recover=${checks})
        elseif(sanitizer STREQUAL "TSAN")
            target_compile_options(${target} PRIVATE -g -fsanitize=thread)
            target_link_options(${target} PRIVATE -fsanitize=thread)
        endif()
    endif()
endfunction()
