function(target_enable_sanitizer target sanitizer)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        if(sanitizer STREQUAL "ASAN")
            target_compile_options(${target} PRIVATE -fsanitize=address -ggdb -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
        elseif(sanitizer STREQUAL "UBSAN")
            set(checks undefined,float-divide-by-zero,implicit-conversion,nullability)
            target_compile_options(${target} PRIVATE -g -fsanitize=${checks} -fno-sanitize-recover=${checks})
            target_link_options(${target} PRIVATE -fsanitize=${checks} -fno-sanitize-recover=${checks})
        elseif(sanitizer STREQUAL "MSAN")
            target_compile_options(${target} PRIVATE -fsanitize=memory -ggdb -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=memory)
        endif()
    endif()
endfunction()

function(test_enable_sanitizer test sanitizer)
    get_test_property(${test} ENVIRONMENT environment)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        if(sanitizer STREQUAL "ASAN")
            # Vulkan on Linux appears to leak memory, so disable leak checks
            list(APPEND environment "ASAN_OPTIONS=detect_leaks=0")
        elseif(sanitizer STREQUAL "UBSAN")
            list(APPEND environment "UBSAN_OPTIONS=print_stacktrace=1")
        endif()
    endif()
    set_tests_properties(${test} PROPERTIES ENVIRONMENT "${environment}" FIXTURES_REQUIRED CppCoverage)
endfunction()
