name: 'install-packages'
description: 'Install pre-built packages from the GitHub Actions cache'

inputs:
  sanitizer:
    description: 'Sanitizer to be used, or OFF to disable'
    required: true
    default: 'OFF'
  fail-on-cache-miss:
    description: "Fail the workflow if the package cache can't be found"
    required: true
    default: 'false'
outputs:
  install-dir:
    description: "Directory the packages were installed to"
    value: ${{ steps.get-dir.outputs.dir }}
  success:
    description: "True if the installion of packages was successful"
    value: ${{ steps.get-status.outputs.success }}

runs:
  using: composite
  steps:
    - name: Determine cache key
      id: get-key
      uses: ./.github/actions/get-packages-cache-key
      with:
        sanitizer: ${{ matrix.sanitizer }}

    - name: Restore packages from cache
      id: cache
      uses: actions/cache/restore@v3
      with:
        key: ${{ steps.get-key.outputs.cache-key }}
        path: './exports'
        fail-on-cache-miss: ${{ inputs.fail-on-cache-miss }}

    - name: Determine install directory
      if: steps.cache.outputs.cache-hit
      id: get-dir
      shell: bash
      run: |
        echo "dir=${{ github.workspace }}/exports/installed/${{ steps.get-key.outputs.triplet }}" >> $GITHUB_OUTPUT

    - name: Determine success status
      id: get-status
      shell: bash
      run: |
        echo success=${{ steps.cache.outputs.cache-hit }} >> $GITHUB_OUTPUT
