name: 'install-packages'
description: 'Install pre-built packages from the GitHub Actions cache'

inputs:
  sanitizer:
    description: 'Sanitizer to be used, or OFF to disable'
    required: true
    default: 'OFF'
outputs:
  install-dir:
    description: "Directory the packages were installed to"
    value: ${{ steps.determine-triplet.outputs.dir }}

runs:
  using: composite
  steps:
    - name: Determine cache key
      id: determine
      uses: ./.github/actions/get-packages-cache-key
      with:
        sanitizer: ${{ matrix.sanitizer }}

    - name: Restore packages from cache
      id: cache
      uses: actions/cache/restore@v3
      with:
        key: ${{ steps.determine.outputs.cache-key }}
        path: './exports'
        fail-on-cache-miss: true
